services:
  - type: web
    name: prime-auction-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # As variáveis abaixo devem ser preenchidas no Dashboard do Render por motivos de segurança
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MPESA_API_KEY
        sync: false
      - key: MPESA_PUBLIC_KEY
        sync: false
      - key: MPESA_C2B_URL
        sync: false
      - key: MPESA_SERVICE_PROVIDER_CODE
        sync: false
